source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SBTUITestTunnel_Example' do
  pod 'SBTUITestTunnel/Server', :path => '../'
  pod 'GCDWebServer', :git=> 'https://github.com/tcamin/GCDWebServer.git'
end

target 'SBTUITestTunnel_Tests' do
  pod 'SBTUITestTunnel/Client', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug' or config.name == 'Release'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1']
      end
    end
  end
end
