source 'https://github.com/CocoaPods/Specs.git'

target 'SBTUITestTunnel_Example', :exclusive => true do
  pod 'SBTUITestTunnel/Server', :path => '../'
end

target 'SBTUITestTunnel_Tests', :exclusive => true do
  pod 'SBTUITestTunnel/Client', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
