source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

def common_pod
  pod 'SBTUITestTunnelCommon', :path => '../'
end

def server_pod
  pod 'SBTUITestTunnelServer', :path => '../'
end

def client_pod
  pod 'SBTUITestTunnelClient', :path => '../'
end

def testing_app_pods
  server_pod
  common_pod

  # SBTUITestTunnelServer depends on GCDWebServer wich is pointed as dependency in SBTUITestTunnelServer.podspec
  # If you need specific version of GCDWebServer
  # uncomment and use next line
  # pod 'GCDWebServer', :git=> 'https://github.com/tcamin/GCDWebServer.git'
end

def tests_pods
  client_pod
end  

target 'SBTUITestTunnel_Example' do
  testing_app_pods

  target 'SBTUITestTunnel_Tests' do
    tests_pods
  end

  target 'SBTUITestTunnel_TestsNoSwizzling' do
    tests_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug' or config.name == 'Release'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1']
      end
    end
  end
end
