name: SBTUITestTunnel

options:
  bundleIdPrefix: com.subito
  groupSortPosition: top
  postGenCommand: "pod install"

fileGroups:
  - SBTUITestTunnel_Example.entitlements

targets:
  SBTUITestTunnel_Example:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      base:
        INFOPLIST_FILE: "SBTUITestTunnel/SBTUITestTunnel-Info.plist"
        CODE_SIGN_ENTITLEMENTS: "SBTUITestTunnel_Example.entitlements"
    sources:
      - path: SBTUITestTunnel
        name: "SBTUITestTunnel_Example"
    dependencies:
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - sdk: CoreGraphics.framework

  SBTUITestTunnel_Tests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      base:
        INFOPLIST_FILE: "SBTUITestTunnel_Tests/Info.plist"
    sources:
      - SBTUITestTunnel_Tests
    dependencies:
      - target: SBTUITestTunnel_Example

  SBTUITestTunnel_TestsNoSwizzling:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "12.2"
    settings:
      base:
        GCC_PREPROCESSOR_DEFINITIONS:
          ["DISABLE_UITUNNEL_SWIZZLING=1", "$(inherited)"]
        INFOPLIST_FILE: "SBTUITestTunnel_TestsNoSwizzling/Info.plist"
    sources:
      - SBTUITestTunnel_TestsNoSwizzling
    dependencies:
      - target: SBTUITestTunnel_Example

schemes:
  SBTUITestTunnel:
    build:
      targets:
        SBTUITestTunnel_Example: [run, test, profile, analyze, archive]
      config: Debug
    profile:
      config: Debug
    test:
      targets:
        - SBTUITestTunnel_Tests
      config: Debug
      gatherCoverageData: true
      disableMainThreadChecker: true
      language: en
      region: EN

  SBTUITestTunnel_Tests:
    run:
      debugEnabled: false
    build:
      targets:
        SBTUITestTunnel_Example: [run, test, profile, analyze, archive]
      config: Debug
    profile:
      config: Debug
    test:
      targets:
        - SBTUITestTunnel_Tests
      config: Debug
      gatherCoverageData: true
      disableMainThreadChecker: true
      debugEnabled: false
      language: en
      region: EN
    management:
      isShown: false

  SBTUITestTunnel_NoSwizzlingTests:
    run:
      debugEnabled: false
    build:
      targets:
        SBTUITestTunnel_Example: [run, test, profile, analyze, archive]
      config: Debug
    profile:
      config: Debug
    test:
      targets:
        - SBTUITestTunnel_TestsNoSwizzling
      config: Debug
      gatherCoverageData: true
      disableMainThreadChecker: true
      debugEnabled: false
      language: en
      region: EN
    management:
      isShown: false
