source "https://cdn.cocoapods.org/"

use_frameworks!
platform :ios, "15.0"

def test_target
  # This is used only for testing purposes
  pod "SBTUITestTunnelServer", :path => "../.."
  # You should normally use SBTUITestTunnelClient only instead
  pod "SBTUITestTunnelClient", :path => "../.."
  pod "SBTUITestTunnelCommon", :path => "../.."
end

target "App" do
  pod "SBTUITestTunnelServer", :path => "../.."
  pod "SBTUITestTunnelCommon", :path => "../.."
end

target "UITests" do
  test_target
end

target "UITestsNoSwizzling" do
  test_target
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["DEPLOYMENT_TARGET"] = "15.0"
    end
  end
end